# dictionary contain keys as incorrect street names and 
# values as correct street names

mapping = {"delhi" : "Delhi",
           "road" : "Road",
           "block" : "Block",
           "sector": "Sector",
           "nagar" : "Nagar",
           "NAGAR" : "Nagar",
           "sadan" : "Sadan",
           "marg" : "Marg",
           "ave" : "Avenue",
           "ave." : "Avenue",
           "vihar" : "Vihar",
           "place" : "Place",
           "colony" : "Colony",
           "chowk" : "Chowk",
           "circle" : "Circle",
           "VIJAY" : "Vijay",
           "II" : "2",
           "–" : "",
           "north" : "North",
           "flat" : "Flat",
          "janakpuri" : "Janakpuri",
          "footpath" : "Footpath",
          "GK" : "Greater Kailash",
          "-" : " ",
          "bazar" : "Bazar",
          "Pahargan" : "Paharganj",}